#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer server

sudo apt-get -y update
sudo apt-get install -y haproxy

server_config
"
backend jay
        balance roundrobin
        server 531517-web-01 54.90.9.3 check
        server 531517-web-02 100.25.183.160 check
frontend jafe
        bind *:80
        mode http
        default_backend jay
"
>>
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy


sudo service haproxy restart
